In [10]:
import pandas as pd
import requests
from datetime import datetime
import pytz

# Solution using a for loop

First we need to take a look at the JSON so we know what we're dealing with.
- We can view what the JSON contains by checking out the [documentation on the OWM website](https://openweathermap.org/forecast5)
- Or this can be done manually, like below:

In [11]:
city = 'Berlin'
API_key = 'put your key here'

# check out the docs for more info on making an api call https://openweathermap.org/forecast5
url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric")

response = requests.get(url)
json = response.json()

json

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1670684400,
   'main': {'temp': -0.74,
    'feels_like': -3.17,
    'temp_min': -1.24,
    'temp_max': -0.74,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 1006,
    'humidity': 89,
    'temp_kf': 0.5},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 98},
   'wind': {'speed': 1.89, 'deg': 31, 'gust': 3.64},
   'visibility': 8961,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-10 15:00:00'},
  {'dt': 1670695200,
   'main': {'temp': -1.38,
    'feels_like': -4.27,
    'temp_min': -1.83,
    'temp_max': -1.38,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 1006,
    'humidity': 88,
    'temp_kf': 0.45},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 97},
   'wind': {'speed': 2.16, 'deg': 26, 'gust': 4.05},
   'visibility': 8870,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-10 18:00:00'},
  {'dt': 1670706000,
   'main': {'temp': -2.37,
    'feels_like': -5.26,
    'temp_min': -2.37,
    'temp_max': -2.37,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1007,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 89},
   'wind': {'speed': 2.03, 'deg': 28, 'gust': 3.63},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-10 21:00:00'},
  {'dt': 1670716800,
   'main': {'temp': -2.64,
    'feels_like': -5.65,
    'temp_min': -2.64,
    'temp_max': -2.64,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 89},
   'wind': {'speed': 2.09, 'deg': 24, 'gust': 3.77},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-11 00:00:00'},
  {'dt': 1670727600,
   'main': {'temp': -3.22,
    'feels_like': -6.45,
    'temp_min': -3.22,
    'temp_max': -3.22,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 83},
   'wind': {'speed': 2.18, 'deg': 16, 'gust': 3.81},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-11 03:00:00'},
  {'dt': 1670738400,
   'main': {'temp': -3.89,
    'feels_like': -7.08,
    'temp_min': -3.89,
    'temp_max': -3.89,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 79},
   'wind': {'speed': 2.07, 'deg': 13, 'gust': 3.64},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-11 06:00:00'},
  {'dt': 1670749200,
   'main': {'temp': -3.38,
    'feels_like': -5.78,
    'temp_min': -3.38,
    'temp_max': -3.38,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1007,
    'humidity': 79,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 36},
   'wind': {'speed': 1.6, 'deg': 38, 'gust': 2.57},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-11 09:00:00'},
  {'dt': 1670760000,
   'main': {'temp': -1.61,
    'feels_like': -4.08,
    'temp_min': -1.61,
    'temp_max': -1.61,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 44},
   'wind': {'speed': 1.82, 'deg': 38, 'gust': 3.07},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-11 12:00:00'},
  {'dt': 1670770800,
   'main': {'temp': -2.5,
    'feels_like': -5.16,
    'temp_min': -2.5,
    'temp_max': -2.5,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 59},
   'wind': {'speed': 1.85, 'deg': 3, 'gust': 3.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-11 15:00:00'},
  {'dt': 1670781600,
   'main': {'temp': -2.76,
    'feels_like': -5.98,
    'temp_min': -2.76,
    'temp_max': -2.76,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 80},
   'wind': {'speed': 2.24, 'deg': 343, 'gust': 4.77},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-11 18:00:00'},
  {'dt': 1670792400,
   'main': {'temp': -2.88,
    'feels_like': -5.67,
    'temp_min': -2.88,
    'temp_max': -2.88,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 1.9, 'deg': 347, 'gust': 3.93},
   'visibility': 10000,
   'pop': 0.33,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-11 21:00:00'},
  {'dt': 1670803200,
   'main': {'temp': -2.43,
    'feels_like': -5.6,
    'temp_min': -2.43,
    'temp_max': -2.43,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 94,
    'temp_kf': 0},
   'weather': [{'id': 600,
     'main': 'Snow',
     'description': 'light snow',
     'icon': '13n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.24, 'deg': 340, 'gust': 4.99},
   'visibility': 2357,
   'pop': 0.44,
   'snow': {'3h': 0.48},
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-12 00:00:00'},
  {'dt': 1670814000,
   'main': {'temp': -2.17,
    'feels_like': -5.48,
    'temp_min': -2.17,
    'temp_max': -2.17,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 95,
    'temp_kf': 0},
   'weather': [{'id': 600,
     'main': 'Snow',
     'description': 'light snow',
     'icon': '13n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.4, 'deg': 319, 'gust': 5.6},
   'visibility': 10000,
   'pop': 0.67,
   'snow': {'3h': 0.11},
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-12 03:00:00'},
  {'dt': 1670824800,
   'main': {'temp': -1.89,
    'feels_like': -5.13,
    'temp_min': -1.89,
    'temp_max': -1.89,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 95,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.38, 'deg': 326, 'gust': 7.07},
   'visibility': 8197,
   'pop': 0.62,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-12 06:00:00'},
  {'dt': 1670835600,
   'main': {'temp': -1.18,
    'feels_like': -4.73,
    'temp_min': -1.18,
    'temp_max': -1.18,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 600,
     'main': 'Snow',
     'description': 'light snow',
     'icon': '13d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.8, 'deg': 316, 'gust': 7.27},
   'visibility': 10000,
   'pop': 0.34,
   'snow': {'3h': 0.14},
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-12 09:00:00'},
  {'dt': 1670846400,
   'main': {'temp': 0.05,
    'feels_like': -3.87,
    'temp_min': 0.05,
    'temp_max': 0.05,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.52, 'deg': 324, 'gust': 7.81},
   'visibility': 10000,
   'pop': 0.3,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-12 12:00:00'},
  {'dt': 1670857200,
   'main': {'temp': -1.01,
    'feels_like': -5.32,
    'temp_min': -1.01,
    'temp_max': -1.01,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.72, 'deg': 309, 'gust': 8.33},
   'visibility': 10000,
   'pop': 0.09,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-12 15:00:00'},
  {'dt': 1670868000,
   'main': {'temp': -1.9,
    'feels_like': -6.2,
    'temp_min': -1.9,
    'temp_max': -1.9,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1007,
    'humidity': 92,
    'temp_kf': 0},
   'weather': [{'id': 600,
     'main': 'Snow',
     'description': 'light snow',
     'icon': '13n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.47, 'deg': 304, 'gust': 7.69},
   'visibility': 3896,
   'pop': 0.35,
   'snow': {'3h': 0.47},
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-12 18:00:00'},
  {'dt': 1670878800,
   'main': {'temp': -2.26,
    'feels_like': -5.95,
    'temp_min': -2.26,
    'temp_max': -2.26,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1008,
    'humidity': 94,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.73, 'deg': 304, 'gust': 6.66},
   'visibility': 10000,
   'pop': 0.22,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-12 21:00:00'},
  {'dt': 1670889600,
   'main': {'temp': -3.04,
    'feels_like': -6.65,
    'temp_min': -3.04,
    'temp_max': -3.04,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1009,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.52, 'deg': 307, 'gust': 6.29},
   'visibility': 10000,
   'pop': 0.07,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-13 00:00:00'},
  {'dt': 1670900400,
   'main': {'temp': -3.88,
    'feels_like': -7.64,
    'temp_min': -3.88,
    'temp_max': -3.88,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 84},
   'wind': {'speed': 2.52, 'deg': 298, 'gust': 6.41},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-13 03:00:00'},
  {'dt': 1670911200,
   'main': {'temp': -4.53,
    'feels_like': -8.39,
    'temp_min': -4.53,
    'temp_max': -4.53,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 71},
   'wind': {'speed': 2.5, 'deg': 293, 'gust': 6.83},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-13 06:00:00'},
  {'dt': 1670922000,
   'main': {'temp': -3.51,
    'feels_like': -7.46,
    'temp_min': -3.51,
    'temp_max': -3.51,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1010,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 54},
   'wind': {'speed': 2.75, 'deg': 283, 'gust': 6.13},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-13 09:00:00'},
  {'dt': 1670932800,
   'main': {'temp': -1.55,
    'feels_like': -5.54,
    'temp_min': -1.55,
    'temp_max': -1.55,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 34},
   'wind': {'speed': 3.2, 'deg': 276, 'gust': 5.2},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-13 12:00:00'},
  {'dt': 1670943600,
   'main': {'temp': -3.26,
    'feels_like': -7.37,
    'temp_min': -3.26,
    'temp_max': -3.26,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 37},
   'wind': {'speed': 2.95, 'deg': 272, 'gust': 6.98},
   'visibility': 10000,
   'pop': 0.08,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-13 15:00:00'},
  {'dt': 1670954400,
   'main': {'temp': -4.56,
    'feels_like': -8.33,
    'temp_min': -4.56,
    'temp_max': -4.56,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1010,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 32},
   'wind': {'speed': 2.42, 'deg': 281, 'gust': 6.29},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-13 18:00:00'},
  {'dt': 1670965200,
   'main': {'temp': -5.38,
    'feels_like': -9.07,
    'temp_min': -5.38,
    'temp_max': -5.38,
    'pressure': 1016,
    'sea_level': 1016,
    'grnd_level': 1010,
    'humidity': 88,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 10},
   'wind': {'speed': 2.25, 'deg': 273, 'gust': 4.52},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-13 21:00:00'},
  {'dt': 1670976000,
   'main': {'temp': -5.96,
    'feels_like': -9.34,
    'temp_min': -5.96,
    'temp_max': -5.96,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 1009,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 10},
   'wind': {'speed': 1.96, 'deg': 263, 'gust': 3.6},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-14 00:00:00'},
  {'dt': 1670986800,
   'main': {'temp': -6.45,
    'feels_like': -8.99,
    'temp_min': -6.45,
    'temp_max': -6.45,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 1008,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 13},
   'wind': {'speed': 1.44, 'deg': 233, 'gust': 2.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-14 03:00:00'},
  {'dt': 1670997600,
   'main': {'temp': -6.83,
    'feels_like': -10.29,
    'temp_min': -6.83,
    'temp_max': -6.83,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 19},
   'wind': {'speed': 1.92, 'deg': 193, 'gust': 3.4},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-14 06:00:00'},
  {'dt': 1671008400,
   'main': {'temp': -5.82,
    'feels_like': -9.61,
    'temp_min': -5.82,
    'temp_max': -5.82,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 28},
   'wind': {'speed': 2.26, 'deg': 179, 'gust': 3.84},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-14 09:00:00'},
  {'dt': 1671019200,
   'main': {'temp': -3.13,
    'feels_like': -6.92,
    'temp_min': -3.13,
    'temp_max': -3.13,
    'pressure': 1012,
    'sea_level': 1012,
    'grnd_level': 1006,
    'humidity': 66,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 16},
   'wind': {'speed': 2.67, 'deg': 183, 'gust': 4.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2022-12-14 12:00:00'},
  {'dt': 1671030000,
   'main': {'temp': -4.81,
    'feels_like': -8.23,
    'temp_min': -4.81,
    'temp_max': -4.81,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 79,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.12, 'deg': 161, 'gust': 4.41},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-14 15:00:00'},
  {'dt': 1671040800,
   'main': {'temp': -5.85,
    'feels_like': -9.75,
    'temp_min': -5.85,
    'temp_max': -5.85,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1006,
    'humidity': 80,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 2.34, 'deg': 166, 'gust': 5.55},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-14 18:00:00'},
  {'dt': 1671051600,
   'main': {'temp': -6.5,
    'feels_like': -10.53,
    'temp_min': -6.5,
    'temp_max': -6.5,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 82,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 2.35, 'deg': 176, 'gust': 5.61},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-14 21:00:00'},
  {'dt': 1671062400,
   'main': {'temp': -6.97,
    'feels_like': -11.03,
    'temp_min': -6.97,
    'temp_max': -6.97,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 77,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 2.31, 'deg': 192, 'gust': 6.07},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-15 00:00:00'},
  {'dt': 1671073200,
   'main': {'temp': -7.27,
    'feels_like': -11.5,
    'temp_min': -7.27,
    'temp_max': -7.27,
    'pressure': 1010,
    'sea_level': 1010,
    'grnd_level': 1005,
    'humidity': 80,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.4, 'deg': 215, 'gust': 6.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-15 03:00:00'},
  {'dt': 1671084000,
   'main': {'temp': -7.33,
    'feels_like': -11.09,
    'temp_min': -7.33,
    'temp_max': -7.33,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 1005,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.06, 'deg': 238, 'gust': 4.28},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2022-12-15 06:00:00'},
  {'dt': 1671094800,
   'main': {'temp': -5.52,
    'feels_like': -8.09,
    'temp_min': -5.52,
    'temp_max': -5.52,
    'pressure': 1013,
    'sea_level': 1013,
    'grnd_level': 1008,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],

Now we've discovered what information we have to work with. Let's decide what we want to keep and what we wish to lose.

I feel that from json['list'] it would be good to keep
- 'weather.main', 'weather.description', 'dt_txt', 'main.temp', 'main.feels_like' 'clouds.all', 'rain.3h', 'snow.3h' 'wind.speed', 'wind.deg', 'main.humidity', 'main.pressure'. 

And from json['city'] it would be good to keep 
- 'name' and 'country. 

Just to make sure that we got the right place. And as an added extra we'll also include the time that API call was made, so we know how up to date our forecast is.

**Optional:** let's get a timestamp of when we get the data. Datetime uses the uses the current time of the system, which on local computers is normally correct. But as we're in the cloud, computers are not always in our country, and we therefore add on the timezone module to ensure that our timestamp is local to us and not the computer.

In [12]:
tz = pytz.timezone('Europe/Berlin')
now = datetime.now().astimezone(tz)

now

datetime.datetime(2022, 12, 10, 13, 53, 11, 198485, tzinfo=<DstTzInfo 'Europe/Berlin' CET+1:00:00 STD>)

**Next** let's loop through the json['list'] information get the weather information

In [13]:
# we'll store the information in this dicitonary:
weather_dict = {'city': [],
                'country': [],
                'forecast_time': [],
                'outlook': [],
                'detailed_outlook': [],
                'temperature': [],
                'temperature_feels_like': [],
                'clouds': [],
                'rain': [],
                'snow': [],
                'wind_speed': [],
                'wind_deg': [],
                'humidity': [],
                'pressure': []}
                #'information_retrieved_at': []}

# let's begin the loop
for i in json['list']:
  weather_dict['city'].append(json['city']['name'])
  weather_dict['country'].append(json['city']['country'])
  weather_dict['forecast_time'].append(i['dt_txt'])
  weather_dict['outlook'].append(i['weather'][0]['main'])
  weather_dict['detailed_outlook'].append(i['weather'][0]['description'])
  weather_dict['temperature'].append(i['main']['temp'])
  weather_dict['temperature_feels_like'].append(i['main']['feels_like'])
  weather_dict['clouds'].append(i['clouds']['all'])
  # sometimes the data is missing for rain and snow. As it is not always raining or snowing
  # we cannot make a DataFrame unless the lists are all the same length, therefore missing values are bad
  # here we say try to append a value if there is one. If not, append a 0
  try:
      weather_dict['rain'].append(i['rain']['3h'])
  except:
      weather_dict['rain'].append('0')
  try:
      weather_dict['snow'].append(i['snow']['3h'])
  except:
      weather_dict['snow'].append('0')
  weather_dict['wind_speed'].append(i['wind']['speed'])
  weather_dict['wind_deg'].append(i['wind']['deg'])
  weather_dict['humidity'].append(i['main']['humidity'])
  weather_dict['pressure'].append(i['main']['pressure'])
  #weather_dict['information_retrieved_at'].append(now.strftime("%d/%m/%Y %H:%M:%S"))

**Now** we convert our dictionary to a DataFrame

In [14]:
weather_from_dict_df = pd.DataFrame(weather_dict)

weather_from_dict_df.head()

,city,country,forecast_time,outlook,detailed_outlook,temperature,temperature_feels_like,clouds,rain,snow,wind_speed,wind_deg,humidity,pressure
0,Berlin,DE,2022-12-10 15:00:00,Clouds,overcast clouds,-0.74,-3.17,98,0,0,1.89,31,89,1004
1,Berlin,DE,2022-12-10 18:00:00,Clouds,overcast clouds,-1.38,-4.27,97,0,0,2.16,26,88,1008
2,Berlin,DE,2022-12-10 21:00:00,Clouds,overcast clouds,-2.37,-5.26,89,0,0,2.03,28,88,1012
3,Berlin,DE,2022-12-11 00:00:00,Clouds,overcast clouds,-2.64,-5.65,89,0,0,2.09,24,87,1012
4,Berlin,DE,2022-12-11 03:00:00,Clouds,broken clouds,-3.22,-6.45,83,0,0,2.18,16,86,1012

**As a final step**, to keep everything tidy: let's bring everything we did together in a function. And allow the function to take a list of cities as an input

In [15]:
def get_weather_loop(cities):

  API_key = 'put your key here'

  tz = pytz.timezone('Europe/Berlin')
  now = datetime.now().astimezone(tz)

  weather_dict = {'city': [],
                'country': [],
                'forecast_time': [],
                'outlook': [],
                'detailed_outlook': [],
                'temperature': [],
                'temperature_feels_like': [],
                'clouds': [],
                'rain': [],
                'snow': [],
                'wind_speed': [],
                'wind_deg': [],
                'humidity': [],
                'pressure': [],
                'information_retrieved_at': []}

  for city in cities:
    url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric")
    response = requests.get(url)
    json = response.json()

    for i in json['list']:
      weather_dict['city'].append(json['city']['name'])
      weather_dict['country'].append(json['city']['country'])
      weather_dict['forecast_time'].append(i['dt_txt'])
      weather_dict['outlook'].append(i['weather'][0]['main'])
      weather_dict['detailed_outlook'].append(i['weather'][0]['description'])
      weather_dict['temperature'].append(i['main']['temp'])
      weather_dict['temperature_feels_like'].append(i['main']['feels_like'])
      weather_dict['clouds'].append(i['clouds']['all'])
      try:
          weather_dict['rain'].append(i['rain']['3h'])
      except:
          weather_dict['rain'].append('0')
      try:
          weather_dict['snow'].append(i['snow']['3h'])
      except:
          weather_dict['snow'].append('0')
      weather_dict['wind_speed'].append(i['wind']['speed'])
      weather_dict['wind_deg'].append(i['wind']['deg'])
      weather_dict['humidity'].append(i['main']['humidity'])
      weather_dict['pressure'].append(i['main']['pressure'])
      weather_dict['information_retrieved_at'].append(now.strftime("%d/%m/%Y %H:%M:%S"))

  return pd.DataFrame(weather_dict)

In [17]:
get_weather_loop(['Berlin', 'London'])

,city,country,forecast_time,outlook,detailed_outlook,temperature,temperature_feels_like,clouds,rain,snow,wind_speed,wind_deg,humidity,pressure,information_retrieved_at
0,Berlin,DE,2022-12-10 15:00:00,Clouds,overcast clouds,-0.74,-3.17,98,0,0,1.89,31,89,1004,10/12/2022 13:53:21
1,Berlin,DE,2022-12-10 18:00:00,Clouds,overcast clouds,-1.38,-4.27,97,0,0,2.16,26,88,1008,10/12/2022 13:53:21
2,Berlin,DE,2022-12-10 21:00:00,Clouds,overcast clouds,-2.37,-5.26,89,0,0,2.03,28,88,1012,10/12/2022 13:53:21
3,Berlin,DE,2022-12-11 00:00:00,Clouds,overcast clouds,-2.64,-5.65,89,0,0,2.09,24,87,1012,10/12/2022 13:53:21
4,Berlin,DE,2022-12-11 03:00:00,Clouds,broken clouds,-3.22,-6.45,83,0,0,2.18,16,86,1012,10/12/2022 13:53:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,London,GB,2022-12-15 00:00:00,Clouds,overcast clouds,2.40,-1.59,100,0,0,4.42,44,69,1010,10/12/2022 13:53:21
76,London,GB,2022-12-15 03:00:00,Clouds,overcast clouds,2.63,-1.32,100,0,0,4.45,40,70,1011,10/12/2022 13:53:21
77,London,GB,2022-12-15 06:00:00,Clouds,overcast clouds,2.99,-1.03,100,0,0,4.73,45,55,1012,10/12/2022 13:53:21
78,London,GB,2022-12-15 09:00:00,Clouds,overcast clouds,2.67,-1.23,91,0,0,4.37,46,52,1014,10/12/2022 13:53:21
79,London,GB,2022-12-15 12:00:00,Clouds,broken clouds,5.02,1.73,65,0,0,4.27,46,48,1015,10/12/2022 13:53:21

In [18]:
weather_data = get_weather_loop (['Berlin', 'Frankfurt', 'Hamburg', 'Paris', 'Brussels', 'Moscow', 'Stockholm', 'Madrid', 'Barcelona'])

In [19]:
weather_data.head()

,city,country,forecast_time,outlook,detailed_outlook,temperature,temperature_feels_like,clouds,rain,snow,wind_speed,wind_deg,humidity,pressure,information_retrieved_at
0,Berlin,DE,2022-12-10 15:00:00,Clouds,overcast clouds,-0.74,-3.17,98,0,0,1.89,31,89,1004,10/12/2022 13:53:39
1,Berlin,DE,2022-12-10 18:00:00,Clouds,overcast clouds,-1.38,-4.27,97,0,0,2.16,26,88,1008,10/12/2022 13:53:39
2,Berlin,DE,2022-12-10 21:00:00,Clouds,overcast clouds,-2.37,-5.26,89,0,0,2.03,28,88,1012,10/12/2022 13:53:39
3,Berlin,DE,2022-12-11 00:00:00,Clouds,overcast clouds,-2.64,-5.65,89,0,0,2.09,24,87,1012,10/12/2022 13:53:39
4,Berlin,DE,2022-12-11 03:00:00,Clouds,broken clouds,-3.22,-6.45,83,0,0,2.18,16,86,1012,10/12/2022 13:53:39

In [20]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   city                      360 non-null    object
 1   country                   360 non-null    object
 2   forecast_time             360 non-null    object
 3   outlook                   360 non-null    object
 4   detailed_outlook          360 non-null    object
 5   temperature               360 non-null    float64
 6   temperature_feels_like    360 non-null    float64
 7   clouds                    360 non-null    int64
 8   rain                      360 non-null    object
 9   snow                      360 non-null    object
 10  wind_speed                360 non-null    float64
 11  wind_deg                  360 non-null    int64
 12  humidity                  360 non-null    int64
 13  pressure                  360 non-null    int64
 14  information_retrieved_at  360 non-null    object
dtypes: float64(3), int64(4), object(8)
memory usage: 42.3+ KB

# Solution using `.json_normalize()`

**First** we need to make an API call to get our information

In [21]:
city = 'Berlin'
API_key = 'put your key here'
url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric") 
response = requests.get(url)
json = response.json()

If we now try to use `.json_normalize()` on the `list` part of the json, you'll see that json_normalize can get confused when it hits a list instead of a subdictionary. Take a look at the weather column below

In [22]:
pd.DataFrame((json['list'])).head()

,dt,main,weather,clouds,wind,visibility,pop,sys,dt_txt,snow
0,1670684400,"{'temp': -0.74, 'feels_like': -3.17, 'temp_min...","[{'id': 804, 'main': 'Clouds', 'description': ...",{'all': 98},"{'speed': 1.89, 'deg': 31, 'gust': 3.64}",8961,0.0,{'pod': 'n'},2022-12-10 15:00:00,NaN
1,1670695200,"{'temp': -1.38, 'feels_like': -4.27, 'temp_min...","[{'id': 804, 'main': 'Clouds', 'description': ...",{'all': 97},"{'speed': 2.16, 'deg': 26, 'gust': 4.05}",8870,0.0,{'pod': 'n'},2022-12-10 18:00:00,NaN
2,1670706000,"{'temp': -2.37, 'feels_like': -5.26, 'temp_min...","[{'id': 804, 'main': 'Clouds', 'description': ...",{'all': 89},"{'speed': 2.03, 'deg': 28, 'gust': 3.63}",10000,0.0,{'pod': 'n'},2022-12-10 21:00:00,NaN
3,1670716800,"{'temp': -2.64, 'feels_like': -5.65, 'temp_min...","[{'id': 804, 'main': 'Clouds', 'description': ...",{'all': 89},"{'speed': 2.09, 'deg': 24, 'gust': 3.77}",10000,0.0,{'pod': 'n'},2022-12-11 00:00:00,NaN
4,1670727600,"{'temp': -3.22, 'feels_like': -6.45, 'temp_min...","[{'id': 803, 'main': 'Clouds', 'description': ...",{'all': 83},"{'speed': 2.18, 'deg': 16, 'gust': 3.81}",10000,0.0,{'pod': 'n'},2022-12-11 03:00:00,NaN

To fix this we need to flatten the nested list using the parameter `record_path`, and then select the other columns we'd like using the parameter `meta`. At the end of the json_normalize parameters we have `errors='ignore'`, which means that if ever there is a missing value in the JSON, a `NaN` gets inserted into the table.Mor information in the [docs](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html)

In [23]:
json_norm_df_1 = pd.json_normalize(json['list'], record_path = ['weather'])
json_norm_df_1.head()

    id    main      description icon
0  804  Clouds  overcast clouds  04n
1  804  Clouds  overcast clouds  04n
2  804  Clouds  overcast clouds  04n
3  804  Clouds  overcast clouds  04n
4  803  Clouds    broken clouds  04n

In [24]:
json_norm_df = pd.json_normalize(json['list'], 
                                record_path=['weather'], 
                                meta=['dt_txt', ['main', 'temp'], ['main', 'feels_like'], 
                                     ['clouds', 'all'], ['rain', '3h'], ['snow', '3h'], ['wind', 'speed'], 
                                     ['wind', 'deg'], ['main', 'humidity'], ['main', 'pressure']],
                                errors='ignore')

json_norm_df.head()

,id,main,description,icon,dt_txt,main.temp,main.feels_like,clouds.all,rain.3h,snow.3h,wind.speed,wind.deg,main.humidity,main.pressure
0,804,Clouds,overcast clouds,04n,2022-12-10 15:00:00,-0.74,-3.17,98,NaN,NaN,1.89,31,89,1004
1,804,Clouds,overcast clouds,04n,2022-12-10 18:00:00,-1.38,-4.27,97,NaN,NaN,2.16,26,88,1008
2,804,Clouds,overcast clouds,04n,2022-12-10 21:00:00,-2.37,-5.26,89,NaN,NaN,2.03,28,88,1012
3,804,Clouds,overcast clouds,04n,2022-12-11 00:00:00,-2.64,-5.65,89,NaN,NaN,2.09,24,87,1012
4,803,Clouds,broken clouds,04n,2022-12-11 03:00:00,-3.22,-6.45,83,NaN,NaN,2.18,16,86,1012

Now let's tidy this DataFrame up by
- dropping some columns
- renaming some columns
- adding some columns

In [25]:
# drop id and icon
json_norm_df = json_norm_df.drop(columns=['id', 'icon']).copy()

In [26]:
# rename some columns
json_norm_df.rename(columns={'main': 'outlook',
                             'description': 'detailed_outlook',
                             'dt_txt': 'forecast_time',
                             'main.temp': 'temperature',
                             'main.feels_like': 'temperature_feels_like',
                             'clouds.all': 'clouds',
                             'rain.3h': 'rain',
                             'snow.3h': 'snow',
                             'wind.speed': 'wind_speed',
                             'wind.deg': 'wind_deg',
                             'main.humidity': 'humidity',
                             'main.pressure': 'pressure',},
                    inplace=True)

In [27]:
# add some columns
json_norm_df.insert(0, 'city', json['city']['name'])
json_norm_df.insert(1, 'country', json['city']['country'])
json_norm_df['information_retrieved_at'] = now.strftime("%d/%m/%Y %H:%M:%S")

# rearrange the columns
json_norm_df = json_norm_df[['city', 'country', 'forecast_time', 'outlook', 'detailed_outlook',
       'temperature', 'temperature_feels_like', 'clouds', 'rain', 'snow',
       'wind_speed', 'wind_deg', 'humidity', 'pressure',
       'information_retrieved_at']]

json_norm_df.head()

,city,country,forecast_time,outlook,detailed_outlook,temperature,temperature_feels_like,clouds,rain,snow,wind_speed,wind_deg,humidity,pressure,information_retrieved_at
0,Berlin,DE,2022-12-10 15:00:00,Clouds,overcast clouds,-0.74,-3.17,98,NaN,NaN,1.89,31,89,1004,10/12/2022 13:53:11
1,Berlin,DE,2022-12-10 18:00:00,Clouds,overcast clouds,-1.38,-4.27,97,NaN,NaN,2.16,26,88,1008,10/12/2022 13:53:11
2,Berlin,DE,2022-12-10 21:00:00,Clouds,overcast clouds,-2.37,-5.26,89,NaN,NaN,2.03,28,88,1012,10/12/2022 13:53:11
3,Berlin,DE,2022-12-11 00:00:00,Clouds,overcast clouds,-2.64,-5.65,89,NaN,NaN,2.09,24,87,1012,10/12/2022 13:53:11
4,Berlin,DE,2022-12-11 03:00:00,Clouds,broken clouds,-3.22,-6.45,83,NaN,NaN,2.18,16,86,1012,10/12/2022 13:53:11

Now we have a very similar DataFrame to what we had with the for loop. Again, let's put this in a function that can take a list of cities

In [28]:
def get_weather_norm(cities):
  
  API_key = 'put your key here'
  df_list = []

  for city in cities:
    url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric") 
    response = requests.get(url)
    json = response.json()

    json_norm_df = pd.json_normalize(json['list'], 
                                record_path=['weather'], 
                                meta=['dt_txt', ['main', 'temp'], ['main', 'feels_like'], ['clouds', 'all'], ['rain', '3h'], ['snow', '3h'], ['wind', 'speed'], ['wind', 'deg'], ['main', 'humidity'], ['main', 'pressure']], 
                                errors='ignore')
    json_norm_df.drop(columns=['id', 'icon'], inplace=True)
    json_norm_df.rename(columns={'main': 'outlook',
                             'description': 'detailed_outlook',
                             'dt_txt': 'forecast_time',
                             'main.temp': 'temperature',
                             'main.feels_like': 'temperature_feels_like',
                             'clouds.all': 'clouds',
                             'rain.3h': 'rain',
                             'snow.3h': 'snow',
                             'wind.speed': 'wind_speed',
                             'wind.deg': 'wind_deg',
                             'main.humidity': 'humidity',
                             'main.pressure': 'pressure',},
                    inplace=True)
    json_norm_df.insert(0, 'city', json['city']['name'])
    json_norm_df.insert(1, 'country', json['city']['country'])
    json_norm_df['information_retrieved_at'] = now.strftime("%d/%m/%Y %H:%M:%S")
    json_norm_df[['city', 'country', 'forecast_time', 'outlook', 'detailed_outlook',
          'temperature', 'temperature_feels_like', 'clouds', 'rain', 'snow',
          'wind_speed', 'wind_deg', 'humidity', 'pressure',
          'information_retrieved_at']]
    df_list.append(json_norm_df)
  return pd.concat(df_list, ignore_index=True)

In [29]:
get_weather_norm(['Berlin', 'London'])

,city,country,outlook,detailed_outlook,forecast_time,temperature,temperature_feels_like,clouds,rain,snow,wind_speed,wind_deg,humidity,pressure,information_retrieved_at
0,Berlin,DE,Clouds,overcast clouds,2022-12-10 15:00:00,-0.74,-3.17,98,NaN,NaN,1.89,31,89,1004,10/12/2022 13:53:11
1,Berlin,DE,Clouds,overcast clouds,2022-12-10 18:00:00,-1.38,-4.27,97,NaN,NaN,2.16,26,88,1008,10/12/2022 13:53:11
2,Berlin,DE,Clouds,overcast clouds,2022-12-10 21:00:00,-2.37,-5.26,89,NaN,NaN,2.03,28,88,1012,10/12/2022 13:53:11
3,Berlin,DE,Clouds,overcast clouds,2022-12-11 00:00:00,-2.64,-5.65,89,NaN,NaN,2.09,24,87,1012,10/12/2022 13:53:11
4,Berlin,DE,Clouds,broken clouds,2022-12-11 03:00:00,-3.22,-6.45,83,NaN,NaN,2.18,16,86,1012,10/12/2022 13:53:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,London,GB,Clear,clear sky,2022-12-15 00:00:00,1.15,-2.02,0,NaN,NaN,2.89,19,67,1012,10/12/2022 13:53:11
76,London,GB,Clear,clear sky,2022-12-15 03:00:00,0.11,-2.58,4,NaN,NaN,2.21,355,77,1013,10/12/2022 13:53:11
77,London,GB,Clear,clear sky,2022-12-15 06:00:00,0.05,-3.23,5,NaN,NaN,2.77,9,83,1014,10/12/2022 13:53:11
78,London,GB,Clouds,few clouds,2022-12-15 09:00:00,0.61,-2.02,13,NaN,NaN,2.24,7,85,1017,10/12/2022 13:53:11
79,London,GB,Clear,clear sky,2022-12-15 12:00:00,3.01,-0.02,7,NaN,NaN,3.18,10,60,1018,10/12/2022 13:53:11