In [1]:
import pandas as pd
!pip install mysql-connector-python
import requests
import mysql.connector
from datetime import datetime
import pytz

Requirement already satisfied: mysql-connector-python in c:\users\user\anaconda3\lib\site-packages (8.0.28)
Requirement already satisfied: protobuf>=3.0.0 in c:\users\user\anaconda3\lib\site-packages (from mysql-connector-python) (3.20.3)

In [2]:
# define connection details
cnx = mysql.connector.connect(
    user='root',
    password='put your password here', #type your root password here
    host='127.0.0.1', # to connect to your local instance
    database='collected_data' #type the name of the database you want to use here
)

In [3]:
# we use the function of the notebook on the weather API and add the code for pushing the data to the local database
def get_weather_loop_push_mysql(cities):

  API_key = 'put your key here'
  id = 0 
  city_id = 0  
  for city in cities:
    url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric")
    response = requests.get(url)
    json = response.json()
    
    city_id +=1
    
    for i in json['list']:
    
      city = json['city']['name']    
      forecast_time = i['dt_txt']
      forecast_time = datetime.strptime(forecast_time, '%Y-%m-%d %X')
      outlook = i['weather'][0]['main']
      temperature = i['main']['temp']
      temperature_feels_like = i['main']['feels_like']
      try:
          rain = i['rain']['3h']
      except:
          rain = '0'
      wind_speed = i['wind']['speed']
      id += 1
    
      data_to_push = (id, city_id, city, forecast_time, outlook, temperature, temperature_feels_like, wind_speed, rain)
        
      cursor = cnx.cursor()
      query = """
      INSERT INTO weather_data (id, city_id, city, forecast_time, outlook, temperature, temperature_feels_like, 
      wind_speed, rain)
      VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s);
      """
      cursor.execute(query, data_to_push)
      cnx.commit()

In [4]:
# run the function with the cities as arguments
get_weather_loop_push_mysql(['Berlin', 'Frankfurt', 'Hamburg', 'Paris', 'Brussels', 'Moscow', 'Stockholm', 'Madrid', 'Barcelona'])

In [5]:
#these need to be done only once for example if you have a loop these must after the loop
cursor = cnx.cursor()
cursor.close()
cnx.close()

## Another solution using sqlalchemy and create_engine where you don't have to make up a table in SQL beforehand by hand

In [6]:
# first we get the dataframe using the predefined function 
# we already used in the notebook to get the information from API: 

def get_weather_loop_to_df(cities):

  API_key = 'put your key here'

  tz = pytz.timezone('Europe/Berlin')
  now = datetime.now().astimezone(tz)

  weather_dict = {'city': [],
                'country': [],
                'forecast_time': [],
                'outlook': [],
                'detailed_outlook': [],
                'temperature': [],
                'temperature_feels_like': [],
                'clouds': [],
                'rain': [],
                'snow': [],
                'wind_speed': [],
                'wind_deg': [],
                'humidity': [],
                'pressure': [],
                'information_retrieved_at': []}

  for city in cities:
    url = (f"http://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_key}&units=metric")
    response = requests.get(url)
    json = response.json()

    for i in json['list']:
      weather_dict['city'].append(json['city']['name'])
      weather_dict['country'].append(json['city']['country'])
      weather_dict['forecast_time'].append(i['dt_txt'])
      weather_dict['outlook'].append(i['weather'][0]['main'])
      weather_dict['detailed_outlook'].append(i['weather'][0]['description'])
      weather_dict['temperature'].append(i['main']['temp'])
      weather_dict['temperature_feels_like'].append(i['main']['feels_like'])
      weather_dict['clouds'].append(i['clouds']['all'])
      try:
          weather_dict['rain'].append(i['rain']['3h'])
      except:
          weather_dict['rain'].append('0')
      try:
          weather_dict['snow'].append(i['snow']['3h'])
      except:
          weather_dict['snow'].append('0')
      weather_dict['wind_speed'].append(i['wind']['speed'])
      weather_dict['wind_deg'].append(i['wind']['deg'])
      weather_dict['humidity'].append(i['main']['humidity'])
      weather_dict['pressure'].append(i['main']['pressure'])
      weather_dict['information_retrieved_at'].append(now.strftime("%d/%m/%Y %H:%M:%S"))

  return pd.DataFrame(weather_dict)

In [7]:
df = get_weather_loop_to_df(['Berlin', 'Frankfurt', 'Hamburg', 'Paris', 'Brussels', 'Moscow', 'Stockholm', 'Madrid', 'Barcelona'])

In [8]:
df

,city,country,forecast_time,outlook,detailed_outlook,temperature,temperature_feels_like,clouds,rain,snow,wind_speed,wind_deg,humidity,pressure,information_retrieved_at
0,Berlin,DE,2022-12-12 21:00:00,Clouds,broken clouds,-2.13,-6.12,80,0,0,3.06,282,84,1006,12/12/2022 19:04:49
1,Berlin,DE,2022-12-13 00:00:00,Clouds,broken clouds,-3.19,-7.03,51,0,0,2.71,275,88,1009,12/12/2022 19:04:49
2,Berlin,DE,2022-12-13 03:00:00,Clouds,broken clouds,-4.42,-8.09,65,0,0,2.36,268,93,1012,12/12/2022 19:04:49
3,Berlin,DE,2022-12-13 06:00:00,Clouds,broken clouds,-4.48,-8.04,53,0,0,2.27,260,92,1012,12/12/2022 19:04:49
4,Berlin,DE,2022-12-13 09:00:00,Clouds,broken clouds,-3.52,-6.50,82,0,0,1.96,262,77,1013,12/12/2022 19:04:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,Barcelona,ES,2022-12-17 06:00:00,Rain,light rain,12.72,12.24,70,0.49,0,3.21,111,84,1016,12/12/2022 19:04:49
356,Barcelona,ES,2022-12-17 09:00:00,Rain,light rain,12.99,12.43,90,0.33,0,1.77,136,80,1018,12/12/2022 19:04:49
357,Barcelona,ES,2022-12-17 12:00:00,Rain,light rain,13.71,13.12,91,0.21,0,2.21,165,76,1018,12/12/2022 19:04:49
358,Barcelona,ES,2022-12-17 15:00:00,Rain,light rain,14.22,13.60,90,0.12,0,1.82,190,73,1018,12/12/2022 19:04:49
359,Barcelona,ES,2022-12-17 18:00:00,Clouds,overcast clouds,13.43,12.81,95,0,0,1.89,246,76,1019,12/12/2022 19:04:49

In [10]:
# then we use sqlalchemy to create a new table in SQL and push the data 
from sqlalchemy import create_engine

username = "root"
password= "put your password here"  # plain (unescaped) text
host= "127.0.0.1"
database="collected_data"

sqlEngine = create_engine(f'mysql+pymysql://{username}:{password}@{host}/{database}')


dbConnection = sqlEngine.connect()

tableName = 'weather_sqlalchemy'

try:

    frame = df.to_sql(tableName, dbConnection, if_exists='append', index = False);

except ValueError as vx:

    print(vx)

except Exception as ex:   

    print(ex)

else:

    print("The data was pushed sucessfully to Table %s."%tableName);   

finally:

    dbConnection.close()

The data was pushed sucessfully to Table weather_sqlalchemy.